package kr.urbansoft.kursmapper.processor.domain.service.guide

open class KoKRProvider : LanguageProvider {

  override val addFunction = "아래 내용의 함수를 추가해주세요."
  override val addFunctionAndImplementationIt = "매퍼에 함수를 추가한 후, 매핑 로직을 구현해주세요."
  override val addFunctionToMapper = "매퍼에 함수를 추가해주세요."
  override val argumentLackedReferToBelow = "함수에 인자가 부족합니다. 아래 내용을 참고해서 인자를 추가해주세요."
  override val changeArgumentsToFinal = "목적 정의 함수의 인자를 최종 인자로 변경하거나, 최종 인자가 적용된 함수로 대체해주세요."
  override val configInterfaceFQCN = "설정 인터페이스 FQCN"
  override val createMapper = "매퍼를 생성합니다."
  override val createMapperFile = "아래 내용의 매퍼 파일을 생성해주세요."
  override val deleteSandbox = "아래 샌드박스 함수를 삭제해주세요. 샌드박스 매퍼 클래스는 삭제하지 않아도 됩니다."
  override val explanationOfArgumentLacked = "인자 부족 문제는 이 매핑 함수가 다른 매핑 함수를 호출하기 위해 필요한 인자가 부족할 때 발생합니다."
  override val explanationOfPurposeFunctionName = "KursMapper는 목적 정의에 사용한 함수명은 사용하지 않으므로, 실제 설정 인터페이스에 정의된 함수명은 위 함수명과 다를 수 있습니다."
  override val explanationOfSandboxRemoval = "정식 사용자 구현이 이미 존재하는 샌드박스 정의는 미래 혼란 방지를 위해 삭제를 강제합니다."
  override val explanationOfSandboxSignature = "KursMapper는 샌드박스 정의에 사용한 클래스명, 변수명, 함수명은 사용하지 않으므로, 실제 설정 인터페이스에 정의된 내용과 위 내용이 다를 수 있습니다."
  override val fileName = "파일명"
  override val finalArgument = "최종 인자"
  override val finalArgumentFQCN = "최종 인자 FQCN"
  override val functionArgumentFQCN = "함수 인자 FQCN"
  override val implementationRequiredReferToBelow = "함수 구현이 필요합니다. 아래 내용을 참고해서 구현해주세요."
  override val implementHere = "여기에 매핑 로직을 구현해주세요."
  override val important = "중요)"
  override val kursMapperGuideEnd = "====================================================================="
  override val kursMapperGuideStart = "======================== [KursMapper 가이드] ========================"
  override val mapperFQCN = "매퍼 FQCN"
  override val mapperPackage = "매퍼가 위치할 패키지"
  override val openConfigInterfaceFile = "설정 인터페이스 파일을 엽니다."
  override val pasteHere = "이 곳에 '{code: bridge}' 대신 붙여넣으세요."
  override val promotingSandboxReferToBelow = "샌드박스 함수를 정식 매핑 함수로 승격하려면 아래 내용을 참고해서 승격해주세요."
  override val purposeFunction = "목적 정의 함수"
  override val rebuildAfterApprovingSandbox = "샌드박스를 승격한 뒤 다시 빌드해주세요."
  override val rebuildAfterChangingArguments = "목적 정의 함수를 변경한 뒤 다시 빌드해주세요."
  override val rebuildAfterImplementation = "구현이 완료되면 다시 빌드해주세요."
  override val rebuildAfterRemoval = "삭제가 완료되면 다시 빌드해주세요."
  override val reference = "참고)"
  override val replaceFunctionBodyWithIDEFeature = "IDE의 Go to Declaration 기능을 이용하여 샌드박스에 정의했던 매핑 코드를 복사해서 정식 매핑 함수 내용으로 교체하세요."
  override val sandboxOverwrittenReferToBelow = "샌드박스 함수 삭제가 필요합니다. 아래 내용을 참고해서 삭제해주세요."
  override val sourceFQCN = "source FQCN"
  override val targetFQCN = "target FQCN"
  override val whyDeleteSandbox1 = "정식 매핑 함수로 승격한 후에도 기존 샌드박스 매핑 함수를 삭제하지 않으면 삭제 가이드와 함께 컴파일 에러가 발생합니다."
  override val whyDeleteSandbox2 = "이것은 어떤 매핑 함수가 현재 적용되고 있는지에 대한 미래 혼란을 방지하기 위함입니다."
}
