package kr.urbansoft.kursmapper.processor.adapter.outbound

import com.google.devtools.ksp.getClassDeclarationByName
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import java.io.OutputStreamWriter
import java.nio.charset.StandardCharsets
import kr.urbansoft.kursmapper.processor.adapter.infra.registry.TypeNameRegistry
import kr.urbansoft.kursmapper.processor.application.port.outbound.WriteMappingFunctionPort
import kr.urbansoft.kursmapper.processor.application.port.outbound.WriteMappingFunctionPort.Context
import kr.urbansoft.kursmapper.processor.domain.model.function.MappingFunction
import kr.urbansoft.kursmapper.processor.domain.model.kurstype.KursTypeId
import kr.urbansoft.kursmapper.processor.shared.exception.ExceptionMessageSupport
import kr.urbansoft.kursmapper.processor.shared.exception.ExceptionType

class WriteMappingFunctionAdapter(
  private val codeGenerator: CodeGenerator,
  private val kspLogger: KSPLogger,
  private val kspResolver: Resolver,
  private val typeNameRegistry: TypeNameRegistry,
) : WriteMappingFunctionPort {
  private fun fileName(mapperName: String) = "${mapperName}ByKurs"

  override fun Context.write() {
    if (mappingFunctionList.isEmpty()) return
    if (mappingFunctionList.distinctBy { it.sourceId }.size != 1)
      throw ExceptionMessage.ALL_MAPPING_FUNCTIONS_IN_THE_LIST_MUST_SHARE_THE_SAME_SOURCE_ID.create()

    val sourceId = mappingFunctionList.first().sourceId
    val sourceTypeName = typeNameRegistry.getOrNull(sourceId) ?: throw ExceptionMessage.SOURCE_TYPE_NAME_IS_NOT_FOUND.create(sourceId.name.value)
    val source = sourceId.asKursType() ?: throw ExceptionMessage.SOURCE_IS_NOT_FOUND.create(sourceId.name.value)

    val mapperPackageName = source.mapperPackageName.value
    val mapperName = source.mapperName.value
    val mapperClassName = ClassName(mapperPackageName, mapperName)

    FileSpec.builder(packageName = mapperPackageName, fileName = fileName(mapperName))
      .addFileComment("Generated by KursMapper. DO NOT EDIT DIRECTLY.")
      .addAllRequiredImports(mappingFunctionList)
      .addMapperClassIfNotExist(mapperClassName, contextConfig.mapperSourceVariableName.value, sourceTypeName)
      .addFunctionForContextSwitching(contextConfig.contextName.value, sourceTypeName, mapperClassName)
      .addMappingFunctions(mappingFunctionList, mapperClassName, this)
      .writeToFile(mapperPackageName, mapperName, sourceId)
  }

  private fun FileSpec.Builder.addAllRequiredImports(mappingFunctionList: List<MappingFunction>): FileSpec.Builder = apply {
    mappingFunctionList.flatMap { it.importList }.forEach { addImport(it.packageName.value, it.name) }
  }

  private fun FileSpec.Builder.addMapperClassIfNotExist(
    mapperClassName: ClassName,
    mapperSourceVariableName: String,
    sourceTypeName: TypeName,
  ): FileSpec.Builder = apply {
    kspResolver.getClassDeclarationByName(mapperClassName.canonicalName)
      ?: let {
        val valueClassSpec =
          TypeSpec.classBuilder(mapperClassName)
            .addAnnotation(JvmInline::class)
            .addModifiers(KModifier.VALUE)
            .primaryConstructor(FunSpec.constructorBuilder().addParameter(mapperSourceVariableName, sourceTypeName).build())
            .addProperty(PropertySpec.builder(mapperSourceVariableName, sourceTypeName).initializer(mapperSourceVariableName).build())
            .build()
        addType(valueClassSpec)
      }
  }

  private fun FileSpec.Builder.addFunctionForContextSwitching(
    functionName: String,
    sourceTypeName: TypeName,
    mapperClassName: ClassName,
  ): FileSpec.Builder = apply {
    val contextSwitchingFunction =
      FunSpec.builder(functionName).receiver(sourceTypeName).returns(mapperClassName).addStatement("return %T(this)", mapperClassName).build()
    addFunction(contextSwitchingFunction)
  }

  private fun FileSpec.Builder.addMappingFunctions(
    mappingFunctionList: List<MappingFunction>,
    mapperClassName: ClassName,
    context: Context,
  ): FileSpec.Builder = apply {
    mappingFunctionList
      .map { mappingFunction ->
        val target =
          with(context) { mappingFunction.targetId.asKursType() }
            ?: throw ExceptionMessage.TARGET_IS_NOT_FOUND.create(mappingFunction.targetId.name.value)
        mappingFunction to target
      }
      .sortedBy { (_, target) -> target.mappingFunctionName.value }
      .forEach { (mappingFunction, target) ->
        val targetTypeName =
          typeNameRegistry.getOrNull(mappingFunction.targetId)
            ?: throw ExceptionMessage.TARGET_TYPE_NAME_IS_NOT_FOUND.create(mappingFunction.targetId.name.value)
        val mappingFunctionName = if (mappingFunction.sourceId == target.id) "passThrough" else target.mappingFunctionName.value
        val mappingFunctionBuilder =
          FunSpec.builder(mappingFunctionName)
            .receiver(mapperClassName)
            .returns(targetTypeName)
            .addCode(mappingFunction.body.value.takeIf { it.isNotBlank() } ?: "return TODO(\"Implementation required\")")
        mappingFunction.argumentList.forEach { argument ->
          mappingFunctionBuilder.addParameter(
            argument.name.value,
            typeNameRegistry.getOrNull(argument.typeId) ?: throw ExceptionMessage.PARAMETER_TYPE_NAME_IS_NOT_FOUND.create(argument.typeId.name.value),
          )
        }
        addFunction(mappingFunctionBuilder.build())
      }
  }

  private fun FileSpec.Builder.writeToFile(mapperPackageName: String, mapperName: String, sourceId: KursTypeId): FileSpec.Builder = apply {
    val fileSpec = build()
    try {
      val file = codeGenerator.createNewFile(dependencies = Dependencies.ALL_FILES, packageName = mapperPackageName, fileName = fileName(mapperName))
      OutputStreamWriter(file, StandardCharsets.UTF_8).use { writer -> fileSpec.writeTo(writer) }
    } catch (e: FileAlreadyExistsException) {
      val wrappedException = ExceptionMessage.MAPPER_FILE_ALREADY_EXISTS.create(mapperPackageName, fileName(mapperName), sourceId.name.value, e)
      kspLogger.error(wrappedException.message() ?: "Mapper file already exists")
      throw wrappedException
    } catch (e: Exception) {
      throw e
    }
  }

  enum class ExceptionMessage(override val value: String, override val type: ExceptionType) : ExceptionMessageSupport {
    ALL_MAPPING_FUNCTIONS_IN_THE_LIST_MUST_SHARE_THE_SAME_SOURCE_ID(
      "All mapping functions in the list must share the same sourceId.",
      ExceptionType.BAD_REQUEST,
    ),
    MAPPER_FILE_ALREADY_EXISTS(
      "Mapper file already exists: {}.{} for {}\nYou should add @KursRule to escape this conflict.\nPlease refer to README.md if you don't know how to do it.\nurbansoft-kr/kurs-mapper github: https://github.com/urbansoft-kr/kurs-mapper",
      ExceptionType.CONFLICT,
    ),
    SOURCE_IS_NOT_FOUND("source is not found: {}", ExceptionType.NOT_FOUND),
    SOURCE_TYPE_NAME_IS_NOT_FOUND("typeName of source is not found: {}", ExceptionType.NOT_FOUND),
    TARGET_IS_NOT_FOUND("target is not found: {}", ExceptionType.NOT_FOUND),
    TARGET_TYPE_NAME_IS_NOT_FOUND("typeName of target is not found: {}", ExceptionType.NOT_FOUND),
    PARAMETER_TYPE_NAME_IS_NOT_FOUND("typeName of parameter is not found: {}", ExceptionType.NOT_FOUND),
  }
}
